services:
  app_guestbook:
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    networks:
      - traefik_network
    labels:
      - "traefik.enable=false"
    depends_on:
      - mysql
  
  server_guestbook:
    image: nginx:alpine
    container_name: server_guestbook
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - traefik_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server_guestbook.rule=Host(`guest-book.test`)"
      - "traefik.http.routers.server_guestbook.entrypoints=https"
      - "traefik.http.routers.server_guestbook.tls=true"
      - "traefik.http.routers.server_guestbook.service=server_guestbook@docker"
      - "traefik.http.services.server_guestbook.loadbalancer.server.port=80"
    depends_on:
      - app_guestbook

  mysql:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: guestbook_db
      MYSQL_USER: guestbook
      MYSQL_PASSWORD: 12345
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - traefik_network

volumes:
  mysql_data:

networks:
  traefik_network:
    external: true