services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - .:/var/www/html
    command: >
      sh -c "php spark serve --host 0.0.0.0 --port 8081"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`guest-book.test`)"
      - "traefik.http.services.app.loadbalancer.server.port=8081"
    networks:
      - traefik_network
    environment:
      - APP_ENV=development
      - DB_HOST=mysql
      - DB_DATABASE=guestbook_db
      - DB_USERNAME=guestbook
      - DB_PASSWORD=12345
    depends_on:
      - mysql

  mysql:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: guestbook_db
      MYSQL_USER: guestbook
      MYSQL_PASSWORD: 12345
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - traefik_network

volumes:
  mysql_data:

networks:
  traefik_network:
    external: true